// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq-GNn9kd8BUMFsXnxLcoVbmHV6fOOOAc',
    appId: '1:745751160367:web:8018393a492dd07d3a88da',
    messagingSenderId: '745751160367',
    projectId: 'notes-f5ed5',
    authDomain: 'notes-f5ed5.firebaseapp.com',
    storageBucket: 'notes-f5ed5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-5-1Ne0SfW_fcpGdl-GEqxKq9FbzPG24',
    appId: '1:745751160367:android:bf9182bf3e754b1a3a88da',
    messagingSenderId: '745751160367',
    projectId: 'notes-f5ed5',
    storageBucket: 'notes-f5ed5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSb3zvkXoZzWukjoTfLwyPbmehsLiLzaI',
    appId: '1:745751160367:ios:9904b737dba7b3833a88da',
    messagingSenderId: '745751160367',
    projectId: 'notes-f5ed5',
    storageBucket: 'notes-f5ed5.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSb3zvkXoZzWukjoTfLwyPbmehsLiLzaI',
    appId: '1:745751160367:ios:9904b737dba7b3833a88da',
    messagingSenderId: '745751160367',
    projectId: 'notes-f5ed5',
    storageBucket: 'notes-f5ed5.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq-GNn9kd8BUMFsXnxLcoVbmHV6fOOOAc',
    appId: '1:745751160367:web:244d7ed1104d91c13a88da',
    messagingSenderId: '745751160367',
    projectId: 'notes-f5ed5',
    authDomain: 'notes-f5ed5.firebaseapp.com',
    storageBucket: 'notes-f5ed5.firebasestorage.app',
  );
}
