// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYgKMX3PE43Uq6ennyYw4uHlim-Vis90',
    appId: '1:756781367271:web:cf797a9289b434e452c742',
    messagingSenderId: '756781367271',
    projectId: 'notess-2a985',
    authDomain: 'notess-2a985.firebaseapp.com',
    storageBucket: 'notess-2a985.firebasestorage.app',
    measurementId: 'G-YP1FFB5MY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMrUYrPLOiwi6oMnFDJ48Q0WVweVBC3ic',
    appId: '1:756781367271:android:465c5edfe9bcfb0852c742',
    messagingSenderId: '756781367271',
    projectId: 'notess-2a985',
    storageBucket: 'notess-2a985.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHIH20eQSnpMlvTiDTTZ2rv8hLq2LcmnQ',
    appId: '1:756781367271:ios:3c846f28ede8b32752c742',
    messagingSenderId: '756781367271',
    projectId: 'notess-2a985',
    storageBucket: 'notess-2a985.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHIH20eQSnpMlvTiDTTZ2rv8hLq2LcmnQ',
    appId: '1:756781367271:ios:3c846f28ede8b32752c742',
    messagingSenderId: '756781367271',
    projectId: 'notess-2a985',
    storageBucket: 'notess-2a985.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIYgKMX3PE43Uq6ennyYw4uHlim-Vis90',
    appId: '1:756781367271:web:ed2baf45d231697e52c742',
    messagingSenderId: '756781367271',
    projectId: 'notess-2a985',
    authDomain: 'notess-2a985.firebaseapp.com',
    storageBucket: 'notess-2a985.firebasestorage.app',
    measurementId: 'G-D2XZTSSZR4',
  );
}
