// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvORlPw9km27TayKS-HYk56zCGfqyU378',
    appId: '1:266557704586:web:90cb41b90c02921ccaa073',
    messagingSenderId: '266557704586',
    projectId: 'mdpgold-5bc55',
    authDomain: 'mdpgold-5bc55.firebaseapp.com',
    databaseURL: 'https://mdpgold-5bc55-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5bc55.firebasestorage.app',
    measurementId: 'G-3KDGC8W0VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9_ZmtIOIyxmhGzKTiufAnDlC8btIP1xg',
    appId: '1:266557704586:android:6ae0425294fa117dcaa073',
    messagingSenderId: '266557704586',
    projectId: 'mdpgold-5bc55',
    databaseURL: 'https://mdpgold-5bc55-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5bc55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANAz5jTxXuIrC6UIVQmRgw_GDWXQi7A20',
    appId: '1:266557704586:ios:7f504b43e6c0cf63caa073',
    messagingSenderId: '266557704586',
    projectId: 'mdpgold-5bc55',
    databaseURL: 'https://mdpgold-5bc55-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5bc55.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANAz5jTxXuIrC6UIVQmRgw_GDWXQi7A20',
    appId: '1:266557704586:ios:7f504b43e6c0cf63caa073',
    messagingSenderId: '266557704586',
    projectId: 'mdpgold-5bc55',
    databaseURL: 'https://mdpgold-5bc55-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5bc55.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvORlPw9km27TayKS-HYk56zCGfqyU378',
    appId: '1:266557704586:web:5b3e31e19f7f6fdecaa073',
    messagingSenderId: '266557704586',
    projectId: 'mdpgold-5bc55',
    authDomain: 'mdpgold-5bc55.firebaseapp.com',
    databaseURL: 'https://mdpgold-5bc55-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5bc55.firebasestorage.app',
    measurementId: 'G-K8NDZCTLJ7',
  );

}