// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4rGS-70UArqRdaWiG5gxcqziEmJfZNmE',
    appId: '1:215573956763:web:25401d78aa556a1919de3e',
    messagingSenderId: '215573956763',
    projectId: 'daftarbelanja-e31aa',
    authDomain: 'daftarbelanja-e31aa.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-e31aa-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-e31aa.firebasestorage.app',
    measurementId: 'G-D32H8TJWX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcKBfjWAwwIC5PVJub3hX2HFNdr3s4Sbg',
    appId: '1:215573956763:android:7ed36b61ec1ada7219de3e',
    messagingSenderId: '215573956763',
    projectId: 'daftarbelanja-e31aa',
    databaseURL: 'https://daftarbelanja-e31aa-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-e31aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJlqFF3mgM1H6C5t5Vc3d_m9jozPD8sH0',
    appId: '1:215573956763:ios:bf9252e4f1f6d7ff19de3e',
    messagingSenderId: '215573956763',
    projectId: 'daftarbelanja-e31aa',
    databaseURL: 'https://daftarbelanja-e31aa-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-e31aa.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJlqFF3mgM1H6C5t5Vc3d_m9jozPD8sH0',
    appId: '1:215573956763:ios:bf9252e4f1f6d7ff19de3e',
    messagingSenderId: '215573956763',
    projectId: 'daftarbelanja-e31aa',
    databaseURL: 'https://daftarbelanja-e31aa-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-e31aa.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4rGS-70UArqRdaWiG5gxcqziEmJfZNmE',
    appId: '1:215573956763:web:1c6d851904de576419de3e',
    messagingSenderId: '215573956763',
    projectId: 'daftarbelanja-e31aa',
    authDomain: 'daftarbelanja-e31aa.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-e31aa-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-e31aa.firebasestorage.app',
    measurementId: 'G-20EX5G95RG',
  );
}
